package com.xiaobai.dao;

import com.xiaobai.model.EcsConsumer;
import java.util.List;

public interface EcsConsumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_consumer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String consumerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_consumer
     *
     * @mbg.generated
     */
    int insert(EcsConsumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_consumer
     *
     * @mbg.generated
     */
    EcsConsumer selectByPrimaryKey(String consumerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_consumer
     *
     * @mbg.generated
     */
    List<EcsConsumer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_consumer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsConsumer record);
}