package com.xiaobai.dao;

import com.xiaobai.model.EcsDistributionscope;
import java.util.List;

public interface EcsDistributionscopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distributionscope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer distributionArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distributionscope
     *
     * @mbg.generated
     */
    int insert(EcsDistributionscope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distributionscope
     *
     * @mbg.generated
     */
    EcsDistributionscope selectByPrimaryKey(Integer distributionArea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distributionscope
     *
     * @mbg.generated
     */
    List<EcsDistributionscope> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_distributionscope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsDistributionscope record);
}