package com.xiaobai.dao;

import com.xiaobai.model.EcsOrder;
import java.util.List;

public interface EcsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order
     *
     * @mbg.generated
     */
    int insert(EcsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order
     *
     * @mbg.generated
     */
    EcsOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order
     *
     * @mbg.generated
     */
    List<EcsOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsOrder record);
}