package com.xiaobai.dao;

import com.xiaobai.model.EcsProvince;
import java.util.List;

public interface EcsProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_province
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_province
     *
     * @mbg.generated
     */
    int insert(EcsProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_province
     *
     * @mbg.generated
     */
    EcsProvince selectByPrimaryKey(String provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_province
     *
     * @mbg.generated
     */
    List<EcsProvince> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsProvince record);
}