package com.xiaobai.dao;

import com.xiaobai.model.EcsRegion;
import java.util.List;

public interface EcsRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbg.generated
     */
    int insert(EcsRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbg.generated
     */
    EcsRegion selectByPrimaryKey(String regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbg.generated
     */
    List<EcsRegion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsRegion record);
}