package com.xiaobai.dao;

import com.xiaobai.model.EcsRoute;
import java.util.List;

public interface EcsRouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_route
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_route
     *
     * @mbg.generated
     */
    int insert(EcsRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_route
     *
     * @mbg.generated
     */
    EcsRoute selectByPrimaryKey(String routeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_route
     *
     * @mbg.generated
     */
    List<EcsRoute> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_route
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsRoute record);
}