package com.xiaobai.dao;

import com.xiaobai.model.EcsUsergroup;
import java.util.List;

public interface EcsUsergroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_usergroup
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String usergroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_usergroup
     *
     * @mbg.generated
     */
    int insert(EcsUsergroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_usergroup
     *
     * @mbg.generated
     */
    EcsUsergroup selectByPrimaryKey(String usergroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_usergroup
     *
     * @mbg.generated
     */
    List<EcsUsergroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_usergroup
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsUsergroup record);
}