package com.xiaobai.model;

public class EcsAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.admin_id
     *
     * @mbg.generated
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.admin_name
     *
     * @mbg.generated
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.admin_sex
     *
     * @mbg.generated
     */
    private Integer adminSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.usergroup_id
     *
     * @mbg.generated
     */
    private String usergroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.admin_status
     *
     * @mbg.generated
     */
    private Integer adminStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.admin_phone
     *
     * @mbg.generated
     */
    private String adminPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_admin.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.admin_id
     *
     * @return the value of ecs_admin.admin_id
     *
     * @mbg.generated
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.admin_id
     *
     * @param adminId the value for ecs_admin.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.admin_name
     *
     * @return the value of ecs_admin.admin_name
     *
     * @mbg.generated
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.admin_name
     *
     * @param adminName the value for ecs_admin.admin_name
     *
     * @mbg.generated
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.admin_sex
     *
     * @return the value of ecs_admin.admin_sex
     *
     * @mbg.generated
     */
    public Integer getAdminSex() {
        return adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.admin_sex
     *
     * @param adminSex the value for ecs_admin.admin_sex
     *
     * @mbg.generated
     */
    public void setAdminSex(Integer adminSex) {
        this.adminSex = adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.usergroup_id
     *
     * @return the value of ecs_admin.usergroup_id
     *
     * @mbg.generated
     */
    public String getUsergroupId() {
        return usergroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.usergroup_id
     *
     * @param usergroupId the value for ecs_admin.usergroup_id
     *
     * @mbg.generated
     */
    public void setUsergroupId(String usergroupId) {
        this.usergroupId = usergroupId == null ? null : usergroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.admin_status
     *
     * @return the value of ecs_admin.admin_status
     *
     * @mbg.generated
     */
    public Integer getAdminStatus() {
        return adminStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.admin_status
     *
     * @param adminStatus the value for ecs_admin.admin_status
     *
     * @mbg.generated
     */
    public void setAdminStatus(Integer adminStatus) {
        this.adminStatus = adminStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.location
     *
     * @return the value of ecs_admin.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.location
     *
     * @param location the value for ecs_admin.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.address
     *
     * @return the value of ecs_admin.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.address
     *
     * @param address the value for ecs_admin.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.password
     *
     * @return the value of ecs_admin.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.password
     *
     * @param password the value for ecs_admin.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.admin_phone
     *
     * @return the value of ecs_admin.admin_phone
     *
     * @mbg.generated
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.admin_phone
     *
     * @param adminPhone the value for ecs_admin.admin_phone
     *
     * @mbg.generated
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_admin.remark
     *
     * @return the value of ecs_admin.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_admin.remark
     *
     * @param remark the value for ecs_admin.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}