package com.xiaobai.model;

import java.util.Date;

public class EcsConsumer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.consumer_id
     *
     * @mbg.generated
     */
    private String consumerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.consumer_name
     *
     * @mbg.generated
     */
    private String consumerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.consumer_sex
     *
     * @mbg.generated
     */
    private Integer consumerSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.usergroup_id
     *
     * @mbg.generated
     */
    private String usergroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.consumer_phone
     *
     * @mbg.generated
     */
    private String consumerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_consumer.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.consumer_id
     *
     * @return the value of ecs_consumer.consumer_id
     *
     * @mbg.generated
     */
    public String getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.consumer_id
     *
     * @param consumerId the value for ecs_consumer.consumer_id
     *
     * @mbg.generated
     */
    public void setConsumerId(String consumerId) {
        this.consumerId = consumerId == null ? null : consumerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.consumer_name
     *
     * @return the value of ecs_consumer.consumer_name
     *
     * @mbg.generated
     */
    public String getConsumerName() {
        return consumerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.consumer_name
     *
     * @param consumerName the value for ecs_consumer.consumer_name
     *
     * @mbg.generated
     */
    public void setConsumerName(String consumerName) {
        this.consumerName = consumerName == null ? null : consumerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.consumer_sex
     *
     * @return the value of ecs_consumer.consumer_sex
     *
     * @mbg.generated
     */
    public Integer getConsumerSex() {
        return consumerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.consumer_sex
     *
     * @param consumerSex the value for ecs_consumer.consumer_sex
     *
     * @mbg.generated
     */
    public void setConsumerSex(Integer consumerSex) {
        this.consumerSex = consumerSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.usergroup_id
     *
     * @return the value of ecs_consumer.usergroup_id
     *
     * @mbg.generated
     */
    public String getUsergroupId() {
        return usergroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.usergroup_id
     *
     * @param usergroupId the value for ecs_consumer.usergroup_id
     *
     * @mbg.generated
     */
    public void setUsergroupId(String usergroupId) {
        this.usergroupId = usergroupId == null ? null : usergroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.password
     *
     * @return the value of ecs_consumer.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.password
     *
     * @param password the value for ecs_consumer.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.consumer_phone
     *
     * @return the value of ecs_consumer.consumer_phone
     *
     * @mbg.generated
     */
    public String getConsumerPhone() {
        return consumerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.consumer_phone
     *
     * @param consumerPhone the value for ecs_consumer.consumer_phone
     *
     * @mbg.generated
     */
    public void setConsumerPhone(String consumerPhone) {
        this.consumerPhone = consumerPhone == null ? null : consumerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.birthday
     *
     * @return the value of ecs_consumer.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.birthday
     *
     * @param birthday the value for ecs_consumer.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.address
     *
     * @return the value of ecs_consumer.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.address
     *
     * @param address the value for ecs_consumer.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_consumer.remark
     *
     * @return the value of ecs_consumer.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_consumer.remark
     *
     * @param remark the value for ecs_consumer.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}