package com.xiaobai.model;

public class EcsDistributionscope {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_distributionscope.distribution_area
     *
     * @mbg.generated
     */
    private Integer distributionArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_distributionscope.distribution_area_name
     *
     * @mbg.generated
     */
    private String distributionAreaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_distributionscope.distribution_price
     *
     * @mbg.generated
     */
    private Long distributionPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_distributionscope.owned_city_id
     *
     * @mbg.generated
     */
    private String ownedCityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_distributionscope.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_distributionscope.distribution_area
     *
     * @return the value of ecs_distributionscope.distribution_area
     *
     * @mbg.generated
     */
    public Integer getDistributionArea() {
        return distributionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_distributionscope.distribution_area
     *
     * @param distributionArea the value for ecs_distributionscope.distribution_area
     *
     * @mbg.generated
     */
    public void setDistributionArea(Integer distributionArea) {
        this.distributionArea = distributionArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_distributionscope.distribution_area_name
     *
     * @return the value of ecs_distributionscope.distribution_area_name
     *
     * @mbg.generated
     */
    public String getDistributionAreaName() {
        return distributionAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_distributionscope.distribution_area_name
     *
     * @param distributionAreaName the value for ecs_distributionscope.distribution_area_name
     *
     * @mbg.generated
     */
    public void setDistributionAreaName(String distributionAreaName) {
        this.distributionAreaName = distributionAreaName == null ? null : distributionAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_distributionscope.distribution_price
     *
     * @return the value of ecs_distributionscope.distribution_price
     *
     * @mbg.generated
     */
    public Long getDistributionPrice() {
        return distributionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_distributionscope.distribution_price
     *
     * @param distributionPrice the value for ecs_distributionscope.distribution_price
     *
     * @mbg.generated
     */
    public void setDistributionPrice(Long distributionPrice) {
        this.distributionPrice = distributionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_distributionscope.owned_city_id
     *
     * @return the value of ecs_distributionscope.owned_city_id
     *
     * @mbg.generated
     */
    public String getOwnedCityId() {
        return ownedCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_distributionscope.owned_city_id
     *
     * @param ownedCityId the value for ecs_distributionscope.owned_city_id
     *
     * @mbg.generated
     */
    public void setOwnedCityId(String ownedCityId) {
        this.ownedCityId = ownedCityId == null ? null : ownedCityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_distributionscope.remark
     *
     * @return the value of ecs_distributionscope.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_distributionscope.remark
     *
     * @param remark the value for ecs_distributionscope.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}