package com.xiaobai.model;

import java.util.Date;

public class EcsHandover {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_handover.start_city
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_handover.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_handover.garden_city
     *
     * @mbg.generated
     */
    private String gardenCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_handover.handover_status
     *
     * @mbg.generated
     */
    private Integer handoverStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_handover.rise_time
     *
     * @mbg.generated
     */
    private Date riseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_handover.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_handover.start_city
     *
     * @return the value of ecs_handover.start_city
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_handover.start_city
     *
     * @param startCity the value for ecs_handover.start_city
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_handover.end_city
     *
     * @return the value of ecs_handover.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_handover.end_city
     *
     * @param endCity the value for ecs_handover.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_handover.garden_city
     *
     * @return the value of ecs_handover.garden_city
     *
     * @mbg.generated
     */
    public String getGardenCity() {
        return gardenCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_handover.garden_city
     *
     * @param gardenCity the value for ecs_handover.garden_city
     *
     * @mbg.generated
     */
    public void setGardenCity(String gardenCity) {
        this.gardenCity = gardenCity == null ? null : gardenCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_handover.handover_status
     *
     * @return the value of ecs_handover.handover_status
     *
     * @mbg.generated
     */
    public Integer getHandoverStatus() {
        return handoverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_handover.handover_status
     *
     * @param handoverStatus the value for ecs_handover.handover_status
     *
     * @mbg.generated
     */
    public void setHandoverStatus(Integer handoverStatus) {
        this.handoverStatus = handoverStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_handover.rise_time
     *
     * @return the value of ecs_handover.rise_time
     *
     * @mbg.generated
     */
    public Date getRiseTime() {
        return riseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_handover.rise_time
     *
     * @param riseTime the value for ecs_handover.rise_time
     *
     * @mbg.generated
     */
    public void setRiseTime(Date riseTime) {
        this.riseTime = riseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_handover.remark
     *
     * @return the value of ecs_handover.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_handover.remark
     *
     * @param remark the value for ecs_handover.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}