package com.xiaobai.model;

public class EcsOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.order_type
     *
     * @mbg.generated
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.handover_id
     *
     * @mbg.generated
     */
    private String handoverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.goods_weight
     *
     * @mbg.generated
     */
    private Integer goodsWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.mailer
     *
     * @mbg.generated
     */
    private String mailer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.mailing_address
     *
     * @mbg.generated
     */
    private String mailingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.receiving_address
     *
     * @mbg.generated
     */
    private String receivingAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.mailer_phone
     *
     * @mbg.generated
     */
    private String mailerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.consignee
     *
     * @mbg.generated
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.consignee_phone
     *
     * @mbg.generated
     */
    private String consigneePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.start_city
     *
     * @mbg.generated
     */
    private String startCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.midpoint_city
     *
     * @mbg.generated
     */
    private String midpointCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.end_city
     *
     * @mbg.generated
     */
    private String endCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.shipping_price
     *
     * @mbg.generated
     */
    private Long shippingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.distribution_price
     *
     * @mbg.generated
     */
    private Long distributionPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.transpory_price
     *
     * @mbg.generated
     */
    private Long transporyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.total_price
     *
     * @mbg.generated
     */
    private String totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.vehicle_id
     *
     * @mbg.generated
     */
    private String vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.order_id
     *
     * @return the value of ecs_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.order_id
     *
     * @param orderId the value for ecs_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.order_type
     *
     * @return the value of ecs_order.order_type
     *
     * @mbg.generated
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.order_type
     *
     * @param orderType the value for ecs_order.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.handover_id
     *
     * @return the value of ecs_order.handover_id
     *
     * @mbg.generated
     */
    public String getHandoverId() {
        return handoverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.handover_id
     *
     * @param handoverId the value for ecs_order.handover_id
     *
     * @mbg.generated
     */
    public void setHandoverId(String handoverId) {
        this.handoverId = handoverId == null ? null : handoverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.goods_name
     *
     * @return the value of ecs_order.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.goods_name
     *
     * @param goodsName the value for ecs_order.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.goods_weight
     *
     * @return the value of ecs_order.goods_weight
     *
     * @mbg.generated
     */
    public Integer getGoodsWeight() {
        return goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.goods_weight
     *
     * @param goodsWeight the value for ecs_order.goods_weight
     *
     * @mbg.generated
     */
    public void setGoodsWeight(Integer goodsWeight) {
        this.goodsWeight = goodsWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.mailer
     *
     * @return the value of ecs_order.mailer
     *
     * @mbg.generated
     */
    public String getMailer() {
        return mailer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.mailer
     *
     * @param mailer the value for ecs_order.mailer
     *
     * @mbg.generated
     */
    public void setMailer(String mailer) {
        this.mailer = mailer == null ? null : mailer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.mailing_address
     *
     * @return the value of ecs_order.mailing_address
     *
     * @mbg.generated
     */
    public String getMailingAddress() {
        return mailingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.mailing_address
     *
     * @param mailingAddress the value for ecs_order.mailing_address
     *
     * @mbg.generated
     */
    public void setMailingAddress(String mailingAddress) {
        this.mailingAddress = mailingAddress == null ? null : mailingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.receiving_address
     *
     * @return the value of ecs_order.receiving_address
     *
     * @mbg.generated
     */
    public String getReceivingAddress() {
        return receivingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.receiving_address
     *
     * @param receivingAddress the value for ecs_order.receiving_address
     *
     * @mbg.generated
     */
    public void setReceivingAddress(String receivingAddress) {
        this.receivingAddress = receivingAddress == null ? null : receivingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.order_status
     *
     * @return the value of ecs_order.order_status
     *
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.order_status
     *
     * @param orderStatus the value for ecs_order.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.mailer_phone
     *
     * @return the value of ecs_order.mailer_phone
     *
     * @mbg.generated
     */
    public String getMailerPhone() {
        return mailerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.mailer_phone
     *
     * @param mailerPhone the value for ecs_order.mailer_phone
     *
     * @mbg.generated
     */
    public void setMailerPhone(String mailerPhone) {
        this.mailerPhone = mailerPhone == null ? null : mailerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.consignee
     *
     * @return the value of ecs_order.consignee
     *
     * @mbg.generated
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.consignee
     *
     * @param consignee the value for ecs_order.consignee
     *
     * @mbg.generated
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.consignee_phone
     *
     * @return the value of ecs_order.consignee_phone
     *
     * @mbg.generated
     */
    public String getConsigneePhone() {
        return consigneePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.consignee_phone
     *
     * @param consigneePhone the value for ecs_order.consignee_phone
     *
     * @mbg.generated
     */
    public void setConsigneePhone(String consigneePhone) {
        this.consigneePhone = consigneePhone == null ? null : consigneePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.start_city
     *
     * @return the value of ecs_order.start_city
     *
     * @mbg.generated
     */
    public String getStartCity() {
        return startCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.start_city
     *
     * @param startCity the value for ecs_order.start_city
     *
     * @mbg.generated
     */
    public void setStartCity(String startCity) {
        this.startCity = startCity == null ? null : startCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.midpoint_city
     *
     * @return the value of ecs_order.midpoint_city
     *
     * @mbg.generated
     */
    public String getMidpointCity() {
        return midpointCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.midpoint_city
     *
     * @param midpointCity the value for ecs_order.midpoint_city
     *
     * @mbg.generated
     */
    public void setMidpointCity(String midpointCity) {
        this.midpointCity = midpointCity == null ? null : midpointCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.end_city
     *
     * @return the value of ecs_order.end_city
     *
     * @mbg.generated
     */
    public String getEndCity() {
        return endCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.end_city
     *
     * @param endCity the value for ecs_order.end_city
     *
     * @mbg.generated
     */
    public void setEndCity(String endCity) {
        this.endCity = endCity == null ? null : endCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.shipping_price
     *
     * @return the value of ecs_order.shipping_price
     *
     * @mbg.generated
     */
    public Long getShippingPrice() {
        return shippingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.shipping_price
     *
     * @param shippingPrice the value for ecs_order.shipping_price
     *
     * @mbg.generated
     */
    public void setShippingPrice(Long shippingPrice) {
        this.shippingPrice = shippingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.distribution_price
     *
     * @return the value of ecs_order.distribution_price
     *
     * @mbg.generated
     */
    public Long getDistributionPrice() {
        return distributionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.distribution_price
     *
     * @param distributionPrice the value for ecs_order.distribution_price
     *
     * @mbg.generated
     */
    public void setDistributionPrice(Long distributionPrice) {
        this.distributionPrice = distributionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.transpory_price
     *
     * @return the value of ecs_order.transpory_price
     *
     * @mbg.generated
     */
    public Long getTransporyPrice() {
        return transporyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.transpory_price
     *
     * @param transporyPrice the value for ecs_order.transpory_price
     *
     * @mbg.generated
     */
    public void setTransporyPrice(Long transporyPrice) {
        this.transporyPrice = transporyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.total_price
     *
     * @return the value of ecs_order.total_price
     *
     * @mbg.generated
     */
    public String getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.total_price
     *
     * @param totalPrice the value for ecs_order.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice == null ? null : totalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.vehicle_id
     *
     * @return the value of ecs_order.vehicle_id
     *
     * @mbg.generated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.vehicle_id
     *
     * @param vehicleId the value for ecs_order.vehicle_id
     *
     * @mbg.generated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_order.remark
     *
     * @return the value of ecs_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_order.remark
     *
     * @param remark the value for ecs_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}