package com.xiaobai.model;

public class EcsUsergroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_usergroup.usergroup_id
     *
     * @mbg.generated
     */
    private String usergroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_usergroup.usergroup_name
     *
     * @mbg.generated
     */
    private String usergroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_usergroup.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_usergroup.usergroup_id
     *
     * @return the value of ecs_usergroup.usergroup_id
     *
     * @mbg.generated
     */
    public String getUsergroupId() {
        return usergroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_usergroup.usergroup_id
     *
     * @param usergroupId the value for ecs_usergroup.usergroup_id
     *
     * @mbg.generated
     */
    public void setUsergroupId(String usergroupId) {
        this.usergroupId = usergroupId == null ? null : usergroupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_usergroup.usergroup_name
     *
     * @return the value of ecs_usergroup.usergroup_name
     *
     * @mbg.generated
     */
    public String getUsergroupName() {
        return usergroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_usergroup.usergroup_name
     *
     * @param usergroupName the value for ecs_usergroup.usergroup_name
     *
     * @mbg.generated
     */
    public void setUsergroupName(String usergroupName) {
        this.usergroupName = usergroupName == null ? null : usergroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_usergroup.remark
     *
     * @return the value of ecs_usergroup.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_usergroup.remark
     *
     * @param remark the value for ecs_usergroup.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}