package com.xiaobai.model;

import java.util.Date;

public class EcsVehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    private String vehicleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.vehicle_model
     *
     * @mbg.generated
     */
    private String vehicleModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.producing_area
     *
     * @mbg.generated
     */
    private String producingArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.route_id
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.manufacture_date
     *
     * @mbg.generated
     */
    private Date manufactureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.purchasing_date
     *
     * @mbg.generated
     */
    private Date purchasingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_vehicle.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.vehicle_id
     *
     * @return the value of ecs_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    public String getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.vehicle_id
     *
     * @param vehicleId the value for ecs_vehicle.vehicle_id
     *
     * @mbg.generated
     */
    public void setVehicleId(String vehicleId) {
        this.vehicleId = vehicleId == null ? null : vehicleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.vehicle_model
     *
     * @return the value of ecs_vehicle.vehicle_model
     *
     * @mbg.generated
     */
    public String getVehicleModel() {
        return vehicleModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.vehicle_model
     *
     * @param vehicleModel the value for ecs_vehicle.vehicle_model
     *
     * @mbg.generated
     */
    public void setVehicleModel(String vehicleModel) {
        this.vehicleModel = vehicleModel == null ? null : vehicleModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.producing_area
     *
     * @return the value of ecs_vehicle.producing_area
     *
     * @mbg.generated
     */
    public String getProducingArea() {
        return producingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.producing_area
     *
     * @param producingArea the value for ecs_vehicle.producing_area
     *
     * @mbg.generated
     */
    public void setProducingArea(String producingArea) {
        this.producingArea = producingArea == null ? null : producingArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.route_id
     *
     * @return the value of ecs_vehicle.route_id
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.route_id
     *
     * @param routeId the value for ecs_vehicle.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.manufacture_date
     *
     * @return the value of ecs_vehicle.manufacture_date
     *
     * @mbg.generated
     */
    public Date getManufactureDate() {
        return manufactureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.manufacture_date
     *
     * @param manufactureDate the value for ecs_vehicle.manufacture_date
     *
     * @mbg.generated
     */
    public void setManufactureDate(Date manufactureDate) {
        this.manufactureDate = manufactureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.purchasing_date
     *
     * @return the value of ecs_vehicle.purchasing_date
     *
     * @mbg.generated
     */
    public Date getPurchasingDate() {
        return purchasingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.purchasing_date
     *
     * @param purchasingDate the value for ecs_vehicle.purchasing_date
     *
     * @mbg.generated
     */
    public void setPurchasingDate(Date purchasingDate) {
        this.purchasingDate = purchasingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_vehicle.remark
     *
     * @return the value of ecs_vehicle.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_vehicle.remark
     *
     * @param remark the value for ecs_vehicle.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}